### ISSUE TITLE
How to upgrade ES? 

### ISSUE THREAD

**Issue by wimvanleuven** [f500/ansible-elasticsearch#2]
Hey,

was just wondering how to upgrade an ES instance using this ansible playbook. Wouldn't we just have to change the apt line to a state=latest instead of present? 

How do you feel about this? 

I'll try a fork for now and see if that works.
-wim

**Comment by jaspernbrouwer** [comment]
Hi Wim!

Our philosophy is that once a package is installed, it shouldn't upgrade when a play is run again. We use special upgrade plays for that. So that's why `state=present`.

But I think it wouldn't hurt if there's an option to set `state=latest` if someone prefers this. I'll look into that soon!

**Comment by wimvanleuven** [comment]
Hey Jasper,

thanks for the feedback! Care to share such an upgrade play and some info
on how you organize install vs upgrades? I'm interested in the
thoughtprocess because we are in the middle of setting up our infra with
Ansible.

Thanks already!
-wim

**Comment by jaspernbrouwer** [comment]
Our upgrade plays basically perform a dist-upgrade:

```yaml
- apt: upgrade=dist update_cache=yes
```

Nothing fancy here :)

The install plays are more elaborate. They ensure machines have a specific state. These plays can be run multiple times, for instance when we need to change some configuration. We wouldn't want existing packages to be upgraded when we just want the configuration updated.

**Comment by wimvanleuven** [comment]
OK, tnx!

**Comment by wimvanleuven** [comment]
Just wondering ... isn't it more complex than this if you have e.g. plugins
installed etc?
-wim

**Comment by jaspernbrouwer** [comment]
Plugins are a different case indeed. I suggest you have separate roles for the plugins. That would keep this role clean, and plugin roles simple and to the point.

Perhaps an `elasticsearch_plugin` module would be ideal, which would work similarly to other package modules (like `apt`, `npm`, etc). That would be a great addition to this role, but I'm not sure when I can find the time to write such a module (hint! :wink:).

**Comment by wimvanleuven** [comment]
Hey ... don't look at me :-)

Don't know enough of ansible to be able to tackle this + too busy to have
time to do it. But should I create a feature request on github? ;-)
-w

**Comment by jaspernbrouwer** [comment]
Yes, please! Let's keep this one about the option to change the preferred `state`, and open a new one for an `elasticsearch_plugin` module.

**Comment by wimvanleuven** [comment]
Done! Any remarks?

**Comment by jaspernbrouwer** [comment]
Looks good! I'll address this (#2) issue somewhere this week. The other (#3) is going to take a bit longer.

**Comment by jaspernbrouwer** [comment]
Sorry it took so long, I've been a bit busy and it slipped my mind :(

Galaxy will be updated in a few minutes!

**Comment by wimvanleuven** [comment]
No problem. Thanks for the help!
-w
