### ISSUE TITLE
Provide elasticsearch_plugin as ansible module to manage ES plugins

### ISSUE THREAD

**Issue by wimvanleuven** [f500/ansible-elasticsearch#3]
When you install ES on a (number of) servers, you can use our playbook. However, to install additional plugins, as best practice you would setup separate roles for each plugin and implement your own update logic (cfr. https://github.com/f500/ansible-elasticsearch/issues/2).

It would obviously become much more attractive if we would provide an ansible module e.g. `elasticsearch_plugin` to simply state what plugin should be installed, incl. version references and also support state="absent".

**Comment by jaspernbrouwer** [comment]
This module was added to Ansible in version 2.0.
