### ISSUE TITLE
http.cors.enabled is false by default

### ISSUE THREAD

**Issue by Skool** [f500/ansible-elasticsearch#7]
Hi,

In new versions of ES, http.cors.enabled is false by default, so we cant use plugins like paramedic in a remote host.

Is it possible to add « http.cors.enabled: true » in elasticsearch.yml.j2 template file ?

Thanks

**Comment by ramondelafuente** [comment]
I looked into the options, and it turns out there are a lot more `http.settings` than are set in the default (example) configuration file for Elasticsearch. I have added the cors settings here: #8 

I'm currently checking if the result is ok, but if you could confirm also, that would be great.

**Comment by ramondelafuente** [comment]
This is now possible by setting `elasticsearch_http_cors_enabled` to `true`.
